### ISSUE TITLE
001-ADR-Control-Architecture

### ISSUE THREAD

**Issue by HeitorMP** [SEAME-pt/T07-DES_Instrument-Cluster#23]
---
# Configuration of the Controller Hardware in SEA:ME context, to control the Racer "Waveshare" 
parent: Decisions
nav_order: 001
title: Architecture Decision Record

## decision-makers: 
   - Nuno Taboada
   - Heitor Maciel
   - Ivo Marques
   - Antonio Ferreira

## consulted: 
  - Felipe Prezado (fp@seame.pt)
  - Pedro Batista (pb@seame.pt)
  - Paulo Silva (ps@seame.pt)
## informed: 
  - Felipe Prezado (fp@seame.pt)
  - Pedro Batista (pb@seame.pt)
  - Paulo Silva (ps@seame.pt)
---

## Context and Problem Statement

Multiple disciplines in automotive control are the driving force for this ADR. The result of this decision addresses the hardware solution to implement an automotive controller that will provide embedded simple solution, interfacing to sensors, advanced drive system and image processing, algorithms, AI and ML
Considering this implementation will be also driven by the pursuit of knowledge and innovation by the decision-makers, it seems fair that the most elevated factor should be knowledge acquisition.

## Decision Drivers

* the features and settings challenges of multiple hardware platforms
* integration of different types of control hardware, from CPU, GPU and MicroController universe of hardware
* implementation of performance issues when implementing in AI and ML
* simple straight forward way off implementing a one controller solution

## Considered Options

* option 1 : JetSon Nano Okdo (JSNano) with CAN HAT : JSNano/CAN
* option 2 : Raspberry Pi 4B with CAN HAT : RPi/CAN
* option 3 : Arduino/CAN + RPi/CAN
* option 4 : Arduino/CAN + JSNano/CAN
* option 5 : Arduino/CAN (sensors) + RPi/IP + JSNano/CAN/IP 

## Decision Outcome

Chosen option:
 ### option 5 : Arduino/CAN (sensors) + RPi/IP + JSNano/CAN/IP

Because it will provide all technical means to achieve purposes:
- learn multiple platforms
- learn multiple protocols integration
- learn multiple code platforms 
- full implementation

##### Benefits
* The learning journey most likely will fill the knowledge goals
* The requirements will be easier to implement

##### Drawbacks
 * bulkier car
 * complexity and fail pruner
 * tighter schedule

### Confirmation

At the end of the first product, "DES_Instrument _Cluster", the decision shall be confirmed as  VALID or INVALID
with report of of the pros and cons faced during the first product development.

## Pros and Cons of the Options

Alternative option if not confirmed the first decision:
###  option 4 : Arduino/CAN + JSNano/CAN

Because it will provide all technical means to achieve purposes:
- learn multiple platforms
- learn multiple protocols integration
- learn multiple code platforms 
- full implementation

##### Benefits
 * minimal control units solution car
 * complexity simpler
 * easier to comply schedule
 
##### Drawbacks
* The learning journey most likely will end up with some  knowledge gaps compare to the goals
* The requirements will be handle harder and rely on software + OS power

**Comment by afmyhouse** [comment]
---
# Configuration for the Jekyll template "Just the Docs"
parent: Decisions
nav_order: 100
title: ADR Template

# These are optional elements. Feel free to remove any of them.
# status: "{proposed | rejected | accepted | deprecated | … | superseded by ADR-0123"
# date: {YYYY-MM-DD when the decision was last updated}
# decision-makers: {list everyone involved in the decision}
# consulted: {list everyone whose opinions are sought (typically subject-matter experts); and with whom there is a two-way communication}
# informed: {list everyone who is kept up-to-date on progress; and with whom there is a one-way communication}
---


# {short title, representative of solved problem and found solution}

## Context and Problem Statement

{Describe the context and problem statement, e.g., in free form using two to three sentences or in the form of an illustrative story. You may want to articulate the problem in form of a question and add links to collaboration boards or issue management systems.}


## Decision Drivers

* {decision driver 1, e.g., a force, facing concern, …}
* {decision driver 2, e.g., a force, facing concern, …}
* … 

## Considered Options

* {title of option 1}
* {title of option 2}
* {title of option 3}
* … 

## Decision Outcome

Chosen option: "{title of option 1}", because {justification. e.g., only option, which meets k.o. criterion decision driver | which resolves force {force} | … | comes out best (see below)}.


### Consequences

* Good, because {positive consequence, e.g., improvement of one or more desired qualities, …}
* Bad, because {negative consequence, e.g., compromising one or more desired qualities, …}
* … 


### Confirmation

{Describe how the implementation of/compliance with the ADR can/will be confirmed. Are the design that was decided for and its implementation in line with the decision made? E.g., a design/code review or a test with a library such as ArchUnit can help validate this. Not that although we classify this element as optional, it is included in many ADRs.}


## Pros and Cons of the Options

### {title of option 1}


{example | description | pointer to more information | …}

* Good, because {argument a}
* Good, because {argument b}

* Neutral, because {argument c}
* Bad, because {argument d}
* … 

### {title of other option}

{example | description | pointer to more information | …}

* Good, because {argument a}
* Good, because {argument b}
* Neutral, because {argument c}
* Bad, because {argument d}
* …


## More Information

{You might want to provide additional evidence/confidence for the decision outcome here and/or document the team agreement on the decision and/or define when/how this decision the decision should be realized and if/when it should be re-visited. Links to other decisions and resources might appear here as well.}

**Comment by afmyhouse** [comment]
# Decision fundamentals for Controller of EVs :  Overview and Comparison

## 1. Centralized vs. Distributed Control

### Centralized Control
**Definition**: One main ECU processes all inputs and manages outputs for the entire vehicle.

#### Pros
- **Simplified Communication**: Reduces inter-ECU communication overhead.
- **Lower Hardware Cost**: Fewer ECUs and wiring harnesses.
- **Ease of Maintenance**: Centralized updates and debugging.
- **Simpler Synchronization**: All logic resides in one unit.

#### Cons
- **Single Point of Failure**: A failure could bring down the entire system.
- **Scalability Issues**: Adding new features can overload the central processor.
- **Higher Latency**: Increased processing load affects response times.

**Best Fit**: Low-complexity systems or prototypes.

---

### Distributed Control
**Definition**: Multiple ECUs, each handling specific subsystems (e.g., battery management, motor control).

#### Pros
- **Fault Tolerance**: Localized failures don’t affect the entire system.
- **Scalability**: New features can be added without overloading existing ECUs.
- **Reduced Latency**: Local processing minimizes delays.
- **Specialized Functionality**: ECUs are optimized for their specific tasks.

#### Cons
- **Higher Cost**: More ECUs and wiring increase costs.
- **Complex Communication**: Requires robust protocols (e.g., CAN) for coordination.
- **Maintenance Complexity**: Debugging becomes challenging.

**Best Fit**: Complex EV systems with high safety and performance needs.

---

## 2. Generic vs. Embedded Controllers

### Generic Controllers
**Definition**: Off-the-shelf controllers for general-purpose applications.

#### Pros
- **Versatility**: Applicable to a wide range of tasks.
- **Cost-Effective**: Mass production makes them inexpensive.
- **Ease of Use**: Extensive libraries, documentation, and community support.

#### Cons
- **Less Optimized**: May not meet specific EV constraints.
- **Size and Power Constraints**: Larger and more power-hungry.

**Best Fit**: Prototyping or non-critical applications.

---

### Embedded Controllers
**Definition**: Custom controllers designed specifically for EV applications.

#### Pros
- **Highly Optimized**: Tailored for performance, power, and size constraints.
- **Reliability**: Designed for the operational conditions of EVs.
- **Security**: Easier to integrate custom security features.

#### Cons
- **Higher Development Cost**: Requires significant investment in design and testing.
- **Longer Time-to-Market**: Custom solutions take more time to develop.

**Best Fit**: High-performance, safety-critical systems like battery and motor management.

---

## 3. Microcontroller vs. FPGA

### Microcontroller (MCU)
**Definition**: A compact integrated circuit for specific control applications.

#### Pros
- **Cost-Effective**: Affordable and widely available.
- **Low Power Consumption**: Ideal for battery-powered systems.
- **Ease of Development**: Extensive tools and community support.
- **Integrated Peripherals**: Includes ADCs, PWM generators, and communication interfaces.

#### Cons
- **Limited Performance**: Fixed architecture may not handle demanding applications.
- **Lack of Parallelism**: Tasks are executed sequentially.

**Best Fit**: General tasks like managing sensors, simple displays, or low-speed actuators.

---

### FPGA (Field-Programmable Gate Array)
**Definition**: A programmable chip for implementing custom hardware functionality.

#### Pros
- **High Performance**: Parallel processing ensures fast response times.
- **Flexibility**: Can implement custom functionality for unique tasks.
- **Deterministic Behavior**: Precise timing, critical for real-time systems.
- **Longevity**: Can be reprogrammed for future needs.

#### Cons
- **High Cost**: Expensive to develop and power-intensive.
- **Complex Development**: Requires specialized knowledge and tools.
- **Power Consumption**: Higher than microcontrollers.

**Best Fit**: High-performance tasks like motor control or real-time sensor fusion.

---

## 4. Other Comparisons

### ASIC (Application-Specific Integrated Circuit) vs. FPGA
- **ASIC**: Ultra-optimized and efficient, but high development costs and lacks reprogrammability.
- **FPGA**: Flexible and faster to develop, but less efficient for production.

---

## Recommendations by Use Case

| Category               | Controller Type     | Best Fit                                             |
|------------------------|---------------------|-----------------------------------------------------|
| Centralized vs. Distributed | **Distributed**   | High-complexity EV systems with critical safety needs. |
| Generic vs. Embedded   | **Embedded**        | High-performance systems like motor and battery control. |
| Microcontroller vs. FPGA | **Microcontroller**| Simple control tasks like sensors and displays.      |
| Microcontroller vs. FPGA | **FPGA**           | High-speed tasks like motor control or real-time applications. |
| ASIC vs. FPGA          | **FPGA**            | Prototyping or tasks requiring flexibility.          |

---
